adiciona endpoint logout
fiap-net-group/graduation-phase-one pull request #33
Opened 2023-06-01 17:11 UTC by alandlan

Adiciona endpoint na authorizationcontroller

2023-06-03 03:41 UTC, enzotlucas requested changes

2023-06-03 03:41 UTC, enzotlucas commented on src/api/PoliceDepartment.EvidenceManager.API/Features/V1/Controllers/AuthorizationController.cs
o signinManager deveria estar na camada de application, certo?

2023-06-04 12:55 UTC, alandlan commented on src/api/PoliceDepartment.EvidenceManager.API/Features/V1/Controllers/AuthorizationController.cs
removi o singinmanager da controller da api.

2023-06-04 23:31 UTC, enzotlucas approved these changes

2023-06-04 23:31 UTC, merged