Feature/martinobrecht/endpoint create evidence
fiap-net-group/graduation-phase-one pull request #40
Opened 2023-06-05 02:45 UTC by MartinObrecht

2023-06-06 01:03 UTC, enzotlucas requested changes
Foi muito boa a ideia de criar testes unitários para o `automapper`, mas acho que é interessante ter uma validação para a evidência se o `officer` autenticado é dono do `case`.

2023-06-06 01:03 UTC, enzotlucas commented on src/api/PoliceDepartment.EvidenceManager.Application/Evidence/UseCases/CreateEvidence.cs
Validar se `Officer` é dono do `Case`, se não for, retornar `ResponseMessage.Forbid`

2023-06-06 01:05 UTC, enzotlucas commented on src/api/PoliceDepartment.EvidenceManager.Application/Evidence/UseCases/CreateEvidence.cs
Sei que ainda não temos a regra feita, mas precisamos definir como salvar o arquivo da imagem da evidência

2023-06-06 11:47 UTC, MartinObrecht commented on src/api/PoliceDepartment.EvidenceManager.API/Features/V1/Controllers/EvidencesController.cs
verdade, vou incluir.

2023-06-17 16:23 UTC, enzotlucas approved these changes

2023-06-17 16:23 UTC, merged